### PR TITLE
Adding image icons to station base manager

### PR DESCRIPTION
**Pull request by lab596**
Hey! I am pretty new to programming but I saw a recent issue (Issue #44 ) created and wanted to try my best to help. I thought this project was super cool and would love to contribute to it in any way possible. Please go over my changes and let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by xspanger3770** [comment]
Hi! 
I checked your new icons and they are perfect! Exactly what I imagined.

No worries if you are new to programming, that's why I open those `good first issues` for beginners.

Just one little tip: please don't include that `.vscode/settings.json` file. It's probably a settings file generated by your IDE. You can either manually remove it from git tracking or even better - add `.vscode/` to the `.gitignore` file so that nothing from that folder gets included.

Make a new commit without that file and your icons are ready to be merged :)

**Comment by xspanger3770** [comment]
... Also I forgot that there is also a fifth action in the station database manager `RestoreDatabaseAction` that restores the database to default state. Can you possibly add icon for it too? Something like a trash bin would be awesome.

**Comment by lab596** [comment]
Sorry for the mess above, but I believe I have updated the .gitignore and also deleted the .vscode/settings.json file. I was wondering if simply updating the .gitignore would have prevented the .vscode/settings.json file from presenting itself in the pull request? Thanks for the help and let me know if you have any more changes.

**Comment by xspanger3770** [comment]
That's ok.
As far as I know, adding the folder to `.gitignore` is one thing, but as you already git-added that file, it will stay included in git and show in the PR until you remove it manually... in other words it's ok now :)
Also I posted a comment like 1 second before yours about the possibility of adding fifth icon, can you do that? :D

**Comment by lab596** [comment]
Sure, let me know if something like this is good for restore.

**Comment by xspanger3770** [comment]
Yeah that's great icon

**Comment by xspanger3770** [comment]
Good job! Welcome among the contributors.

PS: Didn't even notice you've already added the icon in the previous commit xD and I was having a little discussion about some issue...

**Pull request merged**
