### PR TITLE
Included suggestions and lowered the delta value to 0.05 for smoother…

### PR DESCRIPTION
**Pull request by sindhunaydu**
… transition

### CODE REVIEW

**Comment by xspanger3770** [comment]
Tried different delta values and my 0.15 was indeed too fast, but 0.05 feels too slow - at least for me. It might also be due to mouse settings. I would leave it at lets say 0.12 for now and for the future I would make this value customizable by the users inside settings panel by some kind of slider. The settings panel is another issue for another day so perhaps someone will want to implement it or I'll do it myself.. let's see

**Comment by sindhunaydu** [comment]
Got it. Updated the value to 0.12.

**Comment by xspanger3770** [comment]
Thanks!
Merged the changes and closed the issue. Planning to open more "good first issues" in the future so perhaps you can try someting else later :)

**Comment by sindhunaydu** [comment]
> Thanks! Merged the changes and closed the issue. Planning to open more "good first issues" in the future so perhaps you can try someting else later :)

Thanks @xspanger3770, yes I will keep an eye out :) this was fun!

**Pull request merged**
