### PR TITLE
Expanding on tutorial for downloading and installing #95

### PR DESCRIPTION
**Pull request by CentreMetre**
Updated README.md in root. Added tutorial directory. Added instructions for downloading Java for Windows, Linux, and MacOS. Added instructions for installing Java on Windows and setting environment variables on Windows. Added instructions for downloading and running GlobalQuake. #95

### CODE REVIEW

**Comment by xspanger3770** [comment]
So far looking very promising!

**Comment by xspanger3770** [comment]
Hi!
I looked at your current state of the tutorial and even though all parts are not finished, I think that the tutorial already has good informative value and I would like to merge it. What do you think? Do you want to add something else to it?

**Comment by CentreMetre** [comment]
Yes I think it would be fine to merge. What else do you think needs doing? There's mac which I've set up #125 up for, but if there's anything else you think need adding ill make sure to.

**Comment by xspanger3770** [comment]
Surely, you can leave the MAC tutorial for another time / another person.
The last bit that would be great to complete is in the section of setting environment variables for Linux, I see that it is still under construction, and also to add some kind of link to the tutorial to the main README.md file would be nice to have.

**Comment by CentreMetre** [comment]
Ah yea i complete forgot about the linux environment variables, ill get that done when i can get to an emulator. And ill add the link in the main readme to the tutorial readme.

**Comment by CentreMetre** [comment]
Quick question, how should the link be added, since the URL doesnt yet exist for me to add to the main read me? Should i just put 'link coming soon' or something like that? And then add the link when it gets merged?

**Comment by xspanger3770** [comment]
Ah, you are right about the URL... don't worry, you can put "link coming soon" and I can add it later myself :D

**Comment by YacineBoussoufa** [comment]
Sorry, I haven't followed this PR, will the Tutorial be added to the [Repository Wiki](https://github.com/xspanger3770/GlobalQuake/wiki) or in a Website, if I read well? I think that using the wiki is much better.

For reference [wiki of ObsPy](https://github.com/obspy/obspy/wiki)

**Comment by CentreMetre** [comment]
I think a wiki is a good idea, its a better place for end user documentation i think. Maybe this question would be better as an issue?

**Comment by xspanger3770** [comment]
Wiki definitely sounds like a great idea and I haven't even discovered this functionality yet :D

**Comment by xspanger3770** [comment]
I think that you can edit the wiki right away now. Perhaps create a new page called installation tutorial and paste it there?
Apparently there is no need to have the files inside the folders..

**Comment by CentreMetre** [comment]
Sorry for the bit of delay for such a small outcome, but I think we don't need an environment variable tutorial for Linux since the way Linux handles packages, it just automatically knows where it is since it just installed since the package decides it (in **/usr/**, for ubuntu at least) unless they use a portable/Self compiled version, as opposed to windows where the user can decide where to install it. Also to be honest I think if someone is using Linux and they do use the portable version they probably know how to set this, or if they don't know (I'm also one of the people who doesn't 100% know...) how to look it up.

So I think we can possibly leave this out. Maybe at least just for now and if people do have issues with it we could add it then.

**Comment by xspanger3770** [comment]
I finally got the time to merge your tutorial and integrate it with the current readme. Thanks a lot for your help and I hope many people in the future will find the tutorial helpful :)

**Pull request merged**
